### ISSUE TITLE
plotting issues

### ISSUE THREAD

**Issue by marchtaylor** [quang-huynh/MLZ#2]
I am having a problem controlling some of the plotting outputs from MLZ. 

First, the lines recording par settings in `compare_models` is causing a widow to open on my Linux server even when `figure = FALSE`. Maybe these could be deleted:
https://github.com/quang-huynh/MLZ/blob/f9a6fc799945c128c3351a70a99a796f3837ee1d/R/compare_models.R#L31-L32

Second, I don't seem to be able to control the plot of an MLZ data object very well:
https://github.com/quang-huynh/MLZ/blob/f9a6fc799945c128c3351a70a99a796f3837ee1d/R/methods.R#L142

The function produces 2 plots, but the first one (with length-frequency diagrams) is overwritten by the second one of mean length. Am I missing an argument to be able to select one or the other?

Thanks, Marc

**Comment by quang-huynh** [comment]
@marchtaylor For #1, the issue does not appear in RStudio but rather on the command line. 

For #2, there appears to be an issue when ggplot is interacting with base graphics. I've added argument `type` to the plot method to select either a length frequency or mean length plot.

The `linux` branch should address both. Can you double check? (`devtools::install_github("quang-huynh/MLZ", ref = "linux"`)

**Comment by marchtaylor** [comment]
@quang-huynh - Perfect. Works great now. Thanks for your quick fix. Cheers, Marc
